routes/web.php
<?php

use App\Http\Controllers\BestReplyController;
use App\Http\Controllers\ChannelController;
use App\Http\Controllers\LockThreadsController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\UserAvatarController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ThreadController;
use App\Http\Controllers\RepliesController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ThreadSubscriptionsController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function()
{
	Route::get('/thread/create', [ThreadController::class, 'create'])
        ->name('threads.create');
	Route::post('/threads', [ThreadController::class, 'store'])
        ->name('threads.store');
    Route::patch('/thread/{thread}/update', [ThreadController::class, 'update'])
        ->name('thread.update');
    Route::delete('/threads/{thread}/destroy', [ThreadController::class, 'destroy'])
        ->name('threads.destroy');

    Route::post('/lock-thread/{thread}', [LockThreadsController::class, 'store'])->name('lock-thread.store');
    Route::delete('/lock-thread/{thread}', [LockThreadsController::class, 'destroy'])->name('lock-thread.destroy');

	Route::post('/threads/{channel}/{thread}/replies', [RepliesController::class, 'store'])
        ->name('replies.store');
	Route::delete('/replies/{reply}/destroy', [RepliesController::class, 'destroy'])
        ->name('replies.destroy');
	Route::patch('/replies/{reply}/update', [RepliesController::class, 'update'])
        ->name('replies.update');

    Route::post('{thread:id}/replies/{reply}/best', [BestReplyController::class, 'store'])
        ->name('best-reply.store');

	Route::post('/replies/{reply}/favour', [FavouritesController::class, 'store'])
        ->name('favourites.store');
	Route::delete('/replies/{reply}/unfavour', [FavouritesController::class, 'destroy'])
        ->name('favourites.destroy');


	Route::post('/threads/{channel}/{thread}/subscribe', [ThreadSubscriptionsController::class, 'store'])
        ->name('thread.subscriptions.store');
	Route::delete('/threads/{channel}/{thread}/subscribe', [ThreadSubscriptionsController::class, 'destroy'])
        ->name('thread.subscriptions.destroy');

	Route::get('/profile/notifications/', [NotificationController::class, 'index'])
        ->name('notifications.index');
	Route::delete('/profile/notifications/{notification}', [NotificationController::class, 'destroy'])
        ->name('notification.destroy');

    Route::post('/users', [UsersController::class, 'show'])
        ->name('users.show');

    Route::post('/users/{user}/avatar', [UserAvatarController::class, 'store'])
        ->name('users.avatar.store');

});


Route::get('/', [ChannelController::class, 'index'])
	->name('channels.index');
Route::get('/channel/{channel}', [ChannelController::class, 'show'])
    ->name('channel.show');

Route::get('/threads/search', [SearchController::class, 'show'])
    ->name('search.show');
Route::get('/threads', [ThreadController::class, 'index'])
	->name('threads.index.alias');
Route::get('/threads/{channel}', [ThreadController::class, 'index'])
	->name('channel.index');
Route::get('/threads/{channel}/{thread}', [ThreadController::class, 'show'])
	->name('threads.show');
Route::get('/profile/{user}', [ProfileController::class, 'show'])
	->name('user.profile');
Route::get('/threads/{channel}/{thread}/replies', [RepliesController::class, 'index'])->name('replies.index');

require __DIR__.'/auth.php';

app/Models/Thread.php
<?php

namespace App\Models;

use App\RecordsVisits;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\hasMany;
use Illuminate\Database\Eloquent\Relations\belongsTo;
use Illuminate\Database\Eloquent\Builder;
use App\Traits\RecordsActivity;
use Illuminate\Support\Str;
use Laravel\Scout\Searchable;

class Thread extends Model
{
    use HasFactory, RecordsActivity, RecordsVisits, Searchable;

    protected $with = ['owner', 'channel'];

    protected $appends = ['isSubscribedTo'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('replyCount', function(Builder $builder) {
            $builder->withCount('replies');
        });
        static::deleting(function($thread) {
            $thread->replies->each->delete();
        });
    }

    protected $fillable = [
    	'title',
        'body',
        'user_id',
        'channel_id',
        'slug',
        'best_reply_id',
        'locked'
    ];

    public function replies() : hasMany
    {
    	return $this->hasMany(Replies::class);
    }

    public function owner() : belongsTo
    {
    	return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function scopeFilter(Builder $query, $filters)
    {
        return $filters->apply($query);
    }

    public function subscribe(int $userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?? auth()->user()->id
        ]);

        return $this;
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function unsubscribe(int $userId = null)
    {
        $this->subscriptions()
        ->where(['user_id' => $userId ?? auth()->user()->id])
        ->delete();
    }

    public function getIsSubscribedToAttribute(): bool
    {
        return auth()->user() ? $this->subscriptions()->where('user_id', auth()->user()->id)->exists() : false;
    }

    public function addReply(string $body, int $userId = null)
    {
        if($this->locked === 1) {
            throw new \Exception('Thread locked');
        } else {
            return $this->replies()->create([
                'user_id' => $userId ?? auth()->user()->id,
                'body' => $body
            ]);
        }
    }

    public function hasNewReplies(): bool
    {
        if(!auth()->user()) {
            return false;
        }
        $key = sprintf("users.%s.visits.%s", auth()->user()->id, $this->id);
        return $this->updated_at > cache($key);
    }

    public function setSlugAttribute($value): void
    {
        $slug = Str::slug($value);
        $count = 2;
        while(Thread::where('slug', $slug)->exists()) {
            $slug = Str::slug($value).'-'.$count++;
        }
        $this->attributes['slug'] = $slug;
    }

    public function getRouteKeyName(): String
    {
        return 'slug';
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Thread;
use App\Rules\Recaptcha;
use App\Trending;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use App\Filters\ThreadFilter;
use App\Models\Channel;
use Illuminate\Support\Carbon;
use App\Rules\SpamFree;

class ThreadController extends Controller
{
    public function __construct()
    {
        $this->middleware('emailIsConfirmed')->only('store');
    }

    public function index(Channel $channel = null, ThreadFilter $filters, Request $request, Trending $trending)
    {
        if($channel) {
            $query = $channel->threads()->latest();
        } else {
            $query = Thread::latest();
        }

        $threads = $query->filter($filters)->paginate(7);

        if($request->wantsJson()) {
            return $threads;
        }

        return view('threads.index', [
            'threads' => $threads,
            'trendingThreads' => $trending->get(),
        ]);
    }

    public function create()
    {
        return view('threads.create');
    }

    public function store(Request $request, Recaptcha $recaptcha) : RedirectResponse
    {
        $validDataArray = $this->validate($request, [
            'title' => ['required', 'string', new SpamFree],
            'body' => ['required', 'string', new SpamFree],
            'channel_id' => 'integer|required|exists:channels,id',
            'g-recaptcha-response' => ['required', $recaptcha],
        ]);

        $thread = Thread::create(
            array_merge(
                [
                    'user_id' => auth()->user()->id,
                    'slug' => $validDataArray['title'],
                ],
                $validDataArray
            ));

        return redirect(route('threads.show', [$thread->channel->slug, $thread->slug]))->with('flash', 'Your thread has been published!');
    }

    public function update(Request $request, Thread $thread)
    {
        $this->authorize('update', $thread);

        $validDataArray = $this->validate($request, [
            'title' => ['required', 'string', new SpamFree],
            'body' => ['required', 'string', new SpamFree],
        ]);

        $thread->update($validDataArray);
    }

    public function show(Channel $channel, Thread $thread, Trending $trending)
    {
        if(Auth::check()) {
            $key = sprintf("users.%s.visits.%s", auth()->user()->id ?? null, $thread->id);
            cache()->forever($key, Carbon::now());
        }

        $trending->push($thread);
        $thread->recordVisit();

        return view('threads.show', [
            'thread' => $thread
        ]);
    }

    public function destroy(Thread $thread) : RedirectResponse
    {
        $this->authorize('delete', $thread);
        $thread->delete();
        return redirect(route('threads.index.alias'));
    }
}

resources/views/threads/create.blade.php
@extends('app')
@section('content')
	<div class="w-3/4">
		<form
			action="{{route('threads.store')}}"
			method="POST">
			@csrf
			<x-label>Choose a Channel</x-label>
			<select
				name="channel_id"
				class="w-full rounded-md w-full shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 mb-4" blank_as_first required>
				<option value default>Choose One...</option>
				@foreach($channels as $channel)
					<option
						value="{{$channel->id}}"
						{{old('channel_id') == $channel->id ? 'selected' : ''}}>
						{{$channel->name}}
					</option>
				@endforeach
			</select>
			<x-label>Title</x-label>
			<x-input
				name="title"
				type="text"
				placeholder="Title"
				value="{{old('title')}}"
				required />
			<x-textarea
				placeholder="Have something to say?"
				name="body"></x-textarea>
            <div
                class="g-recaptcha mt-4"
                data-sitekey="6LdmWAcdAAAAAMt89aROqjDB7IyOIgp7WIuCaQaa">
            </div>
            <x-button class="mt-4">Publish</x-button>
		</form>
		@if(count($errors))
			<ul id="form-errors" class="mt-8 py-4 pl-8 bg-red-100">
				@foreach($errors->all() as $error)
					<li class="list-disc">{{$error}}</li>
				@endforeach
			</ul>
		@endif
	</div>
@endsection

resources/views/threads/index.blade.php
@extends('app')
@section('content')
    <div id="thread-index" class="md:flex">
        <div class="w-full md:w-3/4">
            <div class="w-full bg-primary-100 max-w-7xl text-white-100 px-2 py-4 mt-4 flex">
                <div class="w-1/2">
                    <h2 class="font-light font-semibold">Threads</h2>
                </div>
                <div class="w-1/6 hidden sm:block">
                    Owner
                </div>
                <div class="w-1/6 hidden sm:block">
                    Visits
                </div>
                <div class="w-1/6 hidden sm:block">
                    Replies
                </div>
            </div>
            @foreach($threads as $thread)
                <article class="py-4 bg-white-100 border-b-1 border-gray-100">
                    <div class="flex">
                        <div class="w-full sm:w-1/2 px-4 pb-6">
                            <h3 class="text-blue-500 font-semibold hover:underline">
                                <a href="{{route('threads.show', [$thread->channel->slug, $thread->slug])}}">
                                    @if($thread->hasNewReplies())
                                        <strong>{{$thread->title}}</strong>
                                    @else
                                        {{$thread->title}}
                                    @endif
                                </a>
                            </h3>
                            <p class="body text-gray-400">{{substr($thread->body, 0, 75)}}...</p>
                            <div class="sm:hidden pt-4">
                                {{$thread->replies_count}} replies
                            </div>
                        </div>
                        <div class="w-1/6 hidden sm:block">
                            <p class="pr-4">
                                <a href="{{route('user.profile', $thread->owner->username)}}" class="text-blue-900 hover:underline">
                                    {{$thread->owner->name}}
                                </a>
                            </p>
                        </div>
                        <div class="hidden sm:block article-footer flex-1 w-1/6">
                            {{$thread->visits}}
                        </div>
                        <div class="w-1/6 hidden sm:block">
                            {{$thread->replies_count}} replies
                        </div>
                    </div>
                </article>
            @endforeach
            <span class="pt-4 block">{{$threads->render()}}</span>
        </div>
        <div class="w-full md:w-1/4 md:pl-4 mb-8 md:mb-0">
            @include('components.widgets.trending-threads')
        </div>
    </div>
@endsection

resources/views/threads/show.blade.php
@extends('app')
@section('content')
	<thread :thread="{{$thread}}" inline-template>
		<div class="flex">
			<div class="w-3/4 p-4">
                <div>


                    <div
                        v-if="editing"
                        class="mb-4">
                        <input
                            type="text"
                            v-model="form.title"
                            class="w-full rounded-md border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 bg-gray-100 mb-4"
                        >
                        <textarea
                            rows="6"
                            v-model="form.body"
                            class="w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 bg-gray-100 mb-4">
                        </textarea>
                        <x-button
                            type="submit"
                            class="mb-4 bg-blue-500"
                            @click.prevent="updateThread">
                            Update
                        </x-button>
                        <x-button
                            type="submit"
                            class="mb-4 bg-gray-500"
                            @click.prevent="cancelUpdate">
                            Cancel
                        </x-button>
                    </div>


                    <div v-else>
                        <h1 class="text-xl" v-text="title"></h1>
                        <p v-text="body"></p>
                    </div>
                    <div class="replies">
                        <h2 class="text-lg">Replies</h2>
                        <replies
                            @newreply="repliesCount++"
                            @removereply="repliesCount--"
                        />
                    </div>
                </div>
			</div>
			<div class="w-1/4" id="sidebar">
                <div class="flex">
                    <div class="mr-4" v-if="$authorize('isAdmin')">
                        <x-button
                            type="submit"
                            class="mb-4 bg-blue-500"
                            @click.prevent="toggleLock"
                            v-text="locked ? 'Unlock thread' : 'Lock thread'">
                        </x-button>
                    </div>
                    <div>
                        @can('delete', $thread)
                            <form
                                action="{{route('threads.destroy', $thread->slug)}}"
                                method="POST">
                                @csrf
                                {{method_field('DELETE')}}
                                <x-button
                                    type="submit"
                                    class="mb-4 bg-red-800">
                                    {{__('Delete Thread')}}
                                </x-button>
                            </form>
                        @endcan
                    </div>
                </div>
                <div class="flex">
                    <div class="mr-4" v-if="$authorize('isAdmin')">
                        <div>
                            <div v-if="editing">
                                <x-button
                                    class="mb-4 mr-4 bg-green-500"
                                    @click.prevent="editing = true"
                                    disabled
                                >
                                    Edit Thread
                                </x-button>
                            </div>
                            <div v-if="$authorize('owns', {{$thread}})">
                                <div v-if="!editing">
                                    <x-button
                                        class="mb-4 mr-4 bg-green-500"
                                        @click.prevent="editing = true">
                                        Edit Thread
                                    </x-button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				<hr />
				<div class="pt-4">
					<p>This thread was published {{$thread->created_at->diffForHumans()}} by <a href="{{route('user.profile', $thread->owner->username)}}" class="text-blue-900 hover:underline">{{$thread->owner->name}}</a>, and currently has <span v-text="repliesCount"></span> {{Str::plural('reply', $thread->replies_count)}}</p>
				</div>
				<subscribebtn
                    v-if="$authorize('signedIn')"
					:isactive="{{json_encode($thread->isSubscribedTo)}}">
				</subscribebtn>
			</div>
		</div>
	</thread>
@endsection